Add assertSameElements for collections
scalameta/munit pull request #393
Opened 2021-07-15 20:08 UTC by danicheg

Adding `assertSameElements()` for comparison elements of collections.
It also might be useful for comparison collections when `==` equality is not applicable (e.g. `Array[A]`). 
For those collections possible to do plain assertion:
```scala
assert(Array() sameElements Array())
```
but this will lead to a poor error message.

2021-07-15 20:09 UTC, danicheg commented on munit/shared/src/main/scala/munit/Assertions.scala
> +      if (!obtained.iterator.sameElements(expected.toIterator)) {
`.toIterator` here just for back compat with Scala 2.11.

2021-07-21 09:01 UTC, olafurpg requested changes
Thank you for this contribution! I am personally on the fence about this addition since it's possible to achieve similar functionality with

- `assertEquals(a.toSet b.toSet)`
- `assertEquals(a.sorted, b.sorted)`

The benefit of those assertions is that they make it clearer whether you're ignoring only the ordering differences, or duplicate elements as well.

However, I'm not opposed to merging this feature if more people think it would be useful. My biggest reservation is that we'll end up with too many assertions. I want to try to keep the number of assertions small.

2021-07-21 10:10 UTC, danicheg commented on munit/shared/src/main/scala/munit/Assertions.scala
> +   * Note that assertion on unsorted collections will produce an unpredictable result.
I mean that
```scala
val x = List("a" -> 1, "b" -> 2, "c" -> 3, "d" -> 3, "f" -> 4)
val y = Set("a" -> 1, "b" -> 2, "c" -> 3, "d" -> 3, "f" -> 4)
x sameElements y // false
```
and
```scala
val x = List("a" -> 1, "b" -> 2, "c" -> 3, "d" -> 3)
val y = Set("a" -> 1, "b" -> 2, "c" -> 3, "d" -> 3)
x sameElements y // true
```
a really unpredictable behaviour.

2021-07-21 10:41 UTC, danicheg commented
@olafurpg I came to this assertion after the migration of a bunch of libs working with a network where it's common to check some `Array[Byte]`s. As for me, it's good to have this assertion to not convert `Array` to `Seq` and don't use `assert` on equals check. But I agree that it makes sense to don't procreate too many assertions, as we know, it always ends up badly :)

2021-07-21 10:46 UTC, danicheg commented on tests/shared/src/test/scala/munit/CollectionAssertionsFrameworkSuite.scala
> +  test("An assertion fails on collections with different elements".fail) {
Good point. Make me known if that PR will have a chance to get merged, then I'll fix that.

2021-07-22 13:07 UTC, olafurpg commented
@danicheg Would it make sense to create a method `assertArraySameElements` instead? It sounds like this assertion is only relevant for arrays. MUnit already has custom assertions for Double/Float primitives.

2021-07-22 19:14 UTC, danicheg commented
@olafurpg as for me, it's more flexible to have that assertion for `Iterable`s, than only for `Array`s. Another take is checking elements of sequences (or even `Iterable`s) different types (though I don't endorse it).

2021-07-23 07:51 UTC, olafurpg commented
@danicheg would you still want to add this assertion if `assertEquals` had a special case for arrays? See https://github.com/scalameta/munit/issues/339 and examples

- https://github.com/com-lihaoyi/utest/blob/39e8d4cbc0b34f047c0da43c1013bc276bb73082/utest/src/utest/asserts/Asserts.scala#L87
- https://github.com/zio/zio/blob/e18d6bac8e86eb3ea270c469cc75503704cbe9aa/test/shared/src/main/scala-2.x/zio/test/AssertionVariants.scala#L29

2021-07-23 08:18 UTC, danicheg commented
@olafurpg yeah, I think it's a great idea. If you agree, I'll do a PR today. And then no needing for the extra assertion, I guess.

2021-07-26 07:13 UTC, olafurpg commented
@danicheg Thank you for this contribution and bouncing back and forth on ideas. We just merged #395, which improves the error message when an assertion fails on comparison of two arrays with equal values but different references. In the spirit of keeping the number of assertions small, we're not gonna add `assertSameElements`. Instead, I encourage you to write such an assertion in your own projects or alternatively override `def assertEquals` to automatically convert array arguments into normal collections.

2021-07-26 07:13 UTC, closed without merging