Enable -Xlint and -Werror
scalameta/munit pull request #461
Opened 2021-11-26 03:44 UTC by som-snytt

Linting on 2.13 such as required empty args,
inferred Any in sameElements of Array[_],
Timeout is double-valued, avoid Any.equals,
some elements unused, deprecations.
Allow JavaConverters.

Can't use nowarn and unused annotations
under 2.11/2.12.

2021-12-27 10:38 UTC, olafurpg approved these changes
LGTM 👍 Thank you for this contribution! I pushed an empty commit to trigger the CI.

2021-12-27 10:44 UTC, olafurpg requested changes
Is there a way to silence the new warnings when compiling the codebase? I don't like fatal warnings because they are painful to work with when coding locally (example: commenting out a println statement introduces a fatal unused warning). 

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/1408093/147464085-3d481da6-aa90-45d4-99db-b54f7043ad78.png">

2021-12-27 13:31 UTC, som-snytt commented
Thanks for taking a look.

OK, less-fatal warnings. Ideally there would be a turn-key or push-button way to enable that only for continuous integration later in the workflow.

I see I added some `-Wconf`, maybe I forgot to clean-compile. This is only my second time using `-Wconf` outside testing `-Wconf`.

2021-12-28 11:37 UTC, som-snytt commented
Tweaked the scalafix task to use current 2.12. That didn't help warnings, so 2.12. scalac options avoid warning.

Now I've lost the doc command that failed, so I haven't reproduced that.

2024-04-10 22:54 UTC, som-snytt commented
Further exploration of perils of crossbuilding with lints.

2025-07-29 19:43 UTC, closed without merging