feat: respect NO_COLOR env variable
scalameta/munit pull request #651
Opened 2023-04-25 23:42 UTC by susliko

Resolves https://github.com/scalameta/munit/issues/149

This PR makes use of the [NO_COLOR](http://no-color.org/) environment variable, disabling all ansi escapes when `NO_COLOR=1`.

Example:
```scala
//> using scala "2.13.10"
//> using lib "org.scalameta::munit::1.0.0-SNAPSHOT" // published locally

class MyTests extends munit.FunSuite {
  test("foo") {
    assert(2 + 2 == 4)
  }
}
```
<img src="https://user-images.githubusercontent.com/15569000/234430385-41f2870e-6a50-45d9-9908-0c4ba72f74e7.png" width="400" />

2023-04-26 18:45 UTC, susliko commented
@valencik Thank you for taking a look!

> As you can see in the [mima run](https://github.com/scalameta/munit/actions/runs/4803233393/jobs/8547826117?pr=651), this is causing some binary incompatibility issues.

Mima issues were solely caused by the removal of unused escapes from `AnsiColors`. This change is reverted now, CI should be passing

>  It's not clear to me why they changes to JUnitReporter.scala, Lines.scala, or Diff.scala are necessary.

These files had some string concatenations with direct inclusion of ansi codes. This PR refactors them to use `Ansi Colors.c` method instead. Please, let me know, if there is another way to ensure escape codes to be filtered while leaving these files untouched

2023-06-09 06:03 UTC, kitbellew requested changes

2023-06-09 06:03 UTC, kitbellew commented on munit/shared/src/main/scala/munit/internal/console/AnsiColors.scala
> +    if (colorSequence == null || isNoColorEnvSet) s
why is this implementation different from Ansi above? please don't read the env var if colorSequence is null, just like above.

2023-06-09 06:03 UTC, kitbellew commented on munit/shared/src/main/scala/munit/internal/difflib/Diff.scala
> +    sb.append(s" ($obtained, $expected)").append("\n")
looks like you're changing output to use `.c` instead of explicit color manipulation. please do that in a separate PR.

2023-09-22 15:50 UTC, valencik commented
Thank you again for this contribution!
Closing in favour of https://github.com/scalameta/munit/pull/703 which was able to minimize the diff nicely.

2023-09-22 15:50 UTC, closed without merging